Presentation.Web/Models/LocalCommunity/CreateLocalCommunityViewModel.cs
#region Head
// <copyright file="CreateLocalCommunityViewModel.cs" company="IT Minds" year="2015">
//     All rights reserved.
// </copyright>
// <license>
//     Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
// </license>
#endregion
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Presentation.Web.Models.Shared;

namespace Presentation.Web.Models.LocalCommunity
{
    public class CreateLocalCommunityViewModel : CbaListPropertiesViewModel
    {
        public CreateLocalCommunityViewModel()
        {
            IsActive = true;
        }
        [DisplayName("Nummer*")]
        [Required(ErrorMessage = "Skriv nummeret på lokalsamfundet.")]
        public int? Number { get; set; }

        [DisplayName("Navn*")]
        [Required(ErrorMessage = "Skriv navnet på lokalsamfundet.")]
        public string Name { get; set; }
    }
}

Presentation.Web/Models/LocalCommunity/EditLocalCommunityViewModel.cs
#region Head
// <copyright file="IndexLocalCommunityViewModel.cs" company="IT Minds" year="2015">
//     All rights reserved.
// </copyright>
// <license>
//     Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
// </license>
#endregion
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Presentation.Web.Models.Shared;

namespace Presentation.Web.Models.LocalCommunity
{
    public class EditLocalCommunityViewModel : CbaListPropertiesViewModel
    {
        public int Id { get; set; }

        [DisplayName("Nummer*")]
        [Required(ErrorMessage = "Feltet Nummer må ikke være tomt.")]
        public int Number { get; set; }

        [DisplayName("Navn*")]
        [Required(ErrorMessage = "Feltet Navn må ikke være tomt.")]
        public string Name { get; set; }
    }
}

Presentation.Web/Models/LocalCommunity/IndexLocalCommunityViewModel.cs
#region Head
// <copyright file="IndexLocalCommunityViewModel.cs" company="IT Minds" year="2015">
//     All rights reserved.
// </copyright>
// <license>
//     Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
// </license>
#endregion
using System.ComponentModel;
using Presentation.Web.Models.Shared;

namespace Presentation.Web.Models.LocalCommunity
{
    public class IndexLocalCommunityViewModel : CbaListPropertiesViewModel
    {
        public int Id { get; set; }

        [DisplayName("Nummer")]
        public int Number { get; set; }

        [DisplayName("Navn")]
        public string Name { get; set; }
    }
}

Presentation.Web/Controllers/LocalCommunityController.cs
#region Head
// <copyright file="LocalCommunityController.cs" company="IT Minds" year="2015">
//     All rights reserved.
// </copyright>
// <license>
//     Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
// </license>
#endregion

using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using Core.DomainModel;
using Core.DomainServices;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Presentation.Web.Attributes;
using Presentation.Web.Helpers;
using Presentation.Web.Models.LocalCommunity;

namespace Presentation.Web.Controllers
{
    [AuthorizeRoles(UserRole.Admin)]
    public class LocalCommunityController : BaseController
    {
        private readonly IGenericRepository<LocalCommunity> _repo;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        private readonly IAdHelper _adHelper;

        public LocalCommunityController(IGenericRepository<LocalCommunity> repo, IUnitOfWork unitOfWork, IMapper mapper, IAdHelper adHelper)
        {
            _repo = repo;
            _unitOfWork = unitOfWork;
            _mapper = mapper;
            _adHelper = adHelper;
        }

        // GET: LocalCommunity
        public ActionResult Index()
        {
            return View();
        }

        // Til Kendo Grids Ajax kald.
        [HttpPost]
        public ActionResult LocalCommunity_Read([DataSourceRequest] DataSourceRequest request)
        {
            var localCommunities = _repo.AsQueryable().Where(l => !l.IsDeleted);

            var vms = localCommunities.ProjectTo<IndexLocalCommunityViewModel>();

            var localCommunitiesVm = vms.ToDataSourceResult(request);
            return Json(localCommunitiesVm);
        }

        // GET: LocalCommunity/Create
        public ActionResult Create()
        {
            var vm = new CreateLocalCommunityViewModel();
            return View(vm);
        }

        // POST: LocalCommunity/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateLocalCommunityViewModel createLocalCommunityViewModel)
        {
            if (!ModelState.IsValid) return View(createLocalCommunityViewModel);

            var localCommunity = _mapper.Map<LocalCommunity>(createLocalCommunityViewModel);
            localCommunity.CreatedOn = DateTime.Now;
            localCommunity.CreatedBy = _adHelper.Name;

            _repo.Insert(localCommunity);
            _unitOfWork.Save();

            return RedirectToAction("Index");
        }

        // GET: LocalCommunity/Edit/{id}
        public ActionResult Edit(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var localCommunity = _repo.GetByKey(id);
            if (localCommunity == null || localCommunity.IsDeleted) return HttpNotFound();
            SetCreatedModifiedInViewBag(localCommunity);

            var vm = _mapper.Map<EditLocalCommunityViewModel>(localCommunity);

            return View(vm);
        }

        // POST: LocalCommunityEdit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditLocalCommunityViewModel editLocalCommunityViewModel)
        {
            if (!ModelState.IsValid)
            {
                var logger = _repo.GetByKey(editLocalCommunityViewModel.Id) as Logger;
                SetCreatedModifiedInViewBag(logger);
                return View(editLocalCommunityViewModel);
            }

            var localCommunity = _mapper.Map<LocalCommunity>(editLocalCommunityViewModel);
            localCommunity.ModifiedBy = _adHelper.Name;
            localCommunity.ModifiedOn = DateTime.Now;

            _repo.Update(localCommunity);
            _unitOfWork.Save();

            return RedirectToAction("Index");
        }

        // GET: LocalCommunityDelete/5
        public ActionResult Delete(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var localCommunity = _repo.GetByKey(id);
            if (localCommunity == null || localCommunity.IsDeleted) return HttpNotFound();
            SetCreatedModifiedInViewBag(localCommunity);

            var vm = _mapper.Map<IndexLocalCommunityViewModel>(localCommunity);

            return View(vm);
        }

        // POST: LocalCommunityDelete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (id <= 0) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var localCommunity = _repo.GetByKey(id);
            if (localCommunity == null || localCommunity.IsDeleted) return HttpNotFound();

            localCommunity.IsDeleted = true;

            _repo.Update(localCommunity);
            _unitOfWork.Save();

            return RedirectToAction("Index");
        }
    }
}

Presentation.Web/Views/LocalCommunity/Create.cshtml
@model Presentation.Web.Models.LocalCommunity.CreateLocalCommunityViewModel
@{
    ViewBag.Title = "Opret lokalsamfund";
}

<h2>Opret lokalsamfund</h2>
<hr class="hidden-xs" />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.Number, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                @Html.EditorFor(model => model.IsActive, new { htmlAttributes = new { @class = "checkbox" } })
                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Gem" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tilbage til listen", "Index")
</div>

Presentation.Web/Views/LocalCommunity/Delete.cshtml
@model Presentation.Web.Models.LocalCommunity.IndexLocalCommunityViewModel
@{
    ViewBag.Title = "Bekræft sletning";
}

<h2>Bekræft sletning</h2>

@Html.Partial("CreatedModifiedPartialView")
<hr class="hidden-xs" />

<h3>Er du sikker på at du vil slette dette lokalsamfund?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.Number)</dt>
        <dd>@Html.DisplayFor(model => model.Number)</dd>

        <dt>@Html.DisplayNameFor(model => model.Name)</dt>
        <dd>@Html.DisplayFor(model => model.Name)</dd>
        
        <dt>@Html.DisplayNameFor(model => model.IsActive)</dt>
        <dd>@Html.DisplayFor(model => model.IsActive)</dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <input type="submit" value="Slet" class="btn btn-danger" /> @:| @Html.ActionLink("Tilbage til listen", "Index")
    }
</div>

Presentation.Web/Views/LocalCommunity/Edit.cshtml
@model Presentation.Web.Models.LocalCommunity.EditLocalCommunityViewModel
@{
    ViewBag.Title = "Rediger lokalsamfund";
}

<h2>Rediger lokalsamfund</h2>
@Html.Partial("CreatedModifiedPartialView")
<hr class="hidden-xs" />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(model => model.CreatedOn)
    @Html.HiddenFor(model => model.CreatedBy)

    <div class="form-horizontal">
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Number, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-sm-2" })
            <div class="col-sm-10">
                @Html.EditorFor(model => model.IsActive, new { htmlAttributes = new { @class = "checkbox" } })
                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Gem" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tilbage til listen", "Index")
</div>

Presentation.Web/Views/LocalCommunity/Index.cshtml
@using Presentation.Web.Helpers
@model IEnumerable<Presentation.Web.Models.LocalCommunity.IndexLocalCommunityViewModel>
@{
    ViewBag.Title = "Lokalsamfund";
    var gridTitle = "LocalCommunityGrid";
}

<h2>Lokalsamfund</h2>

<div class="container">
    <div class="row">
        <a href="@Url.Action("Create")"><span class="glyphicon glyphicon-plus text-success"></span> Opret lokalsamfund</a>
    </div>
    <hr />
    @(Html.Kendo().Grid<Presentation.Web.Models.LocalCommunity.IndexLocalCommunityViewModel>()
          .Name(gridTitle)
          .Columns(c =>
          {
              c.Bound(col => col.Number);
              c.Bound(col => col.Name);
              c.Bound(col => col.IsActive).ClientTemplate("# if (IsActive === true) { # " +
                                                          "Ja" +
                                                          "# } else { #" +
                                                          "Nej" +
                                                          "# } #");

              c.Template(col => null)
                 .AddCustomButton("<span class=\"glyphicon glyphicon-pencil text-success\"></span>", Url.Action("Edit", "LocalCommunity"))
                 .AddCustomButton("<span class=\"glyphicon glyphicon-remove text-danger\"></span>", Url.Action("Delete", "LocalCommunity")).Width(1);
          })
          .Pageable(pager => pager.PageSizes(new List<int> { 10, 20, 50, 100, 200, 500 }))
          .Sortable()
          .Filterable(x => x.Mode(GridFilterMode.Menu))
          .DataSource(x => x.Ajax().Read(r => r.Action("LocalCommunity_Read", "LocalCommunity")))
    )
</div>

@Scripts.Render("~/Scripts/kendo/KendoTableHelpers.js")

@section scripts
{
    <script>
        $(function () {
            initStatePersistance("@gridTitle");
        });
    </script>
}