Presentation.Web/Models/Search/DateSearchTypeViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Presentation.Web.Models.Search
{
    public enum DateSearchTypeViewModel
    {
        [Display(Name = "1 års gennemgang")]
        OneYearReview,

        [Display(Name = "5 års gennemgang")]
        FiveYearReview
    }
}

Presentation.Web/Controllers/ProjectController.cs
#region Head
// <copyright file="ProjectController.cs" company="IT Minds" year="2015">
//     All rights reserved.
// </copyright>
// <license>
//     Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
// </license>
#endregion
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using Core.DomainModel;
using Core.DomainServices;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Presentation.Web.Filters;
using Presentation.Web.Helpers;
using Presentation.Web.Models;
using Presentation.Web.Models.Project;

namespace Presentation.Web.Controllers
{
    public class ProjectController : BaseController
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IGenericRepository<Project> _projectRepository;
        private readonly IMapper _mapper;
        private readonly IGenericRepository<ProjectDocument> _documentRepository;
        private readonly IGenericRepository<Topic> _topicRepo;
        private readonly IDocumentHelper _documentHelper;
        private readonly IDateTime _dateTime;
        private readonly IGeoCoder _geoCoder;
        private readonly IDawaRepository _dawaRepo;
        private readonly IAdHelper _adHelper;

        public ProjectController(IUnitOfWork unitOfWork,
            IGenericRepository<Project> projectRepository,
            IMapper mapper,
            IGenericRepository<ProjectDocument> documentRepository,
            IGenericRepository<Topic> topicRepo,
            IDocumentHelper documentHelper,
            IDateTime dateTime,
            IGeoCoder geoCoder,
            IDawaRepository dawaRepo,
            IAdHelper adHelper)
        {
            _unitOfWork = unitOfWork;
            _projectRepository = projectRepository;
            _mapper = mapper;
            _documentRepository = documentRepository;
            _topicRepo = topicRepo;
            _documentHelper = documentHelper;
            _dateTime = dateTime;
            _geoCoder = geoCoder;
            _dawaRepo = dawaRepo;
            _adHelper = adHelper;
        }

        // GET: Project
        [PopulateTopics]
        [PopulateStreetTypes]
        [PopulateMunicipalityPriorities]
        [PopulateCouncilPriorities]
        [PopulateProjectStatuses]
        public ActionResult Index()
        {
            //Update server cookie with new client values.
            Response.Cookies["select-awaiting"].Value = Request.Cookies["select-awaiting"].Value ?? "true";

            return View();
        }

        // Til Kendo Grids Ajax kald.
        [HttpPost]
        public ActionResult Project_Read([DataSourceRequest] DataSourceRequest request)
        {
            var projects = _projectRepository.AsQueryable();

            if (Request.Cookies["select-awaiting"] != null && Request.Cookies["select-awaiting"].Value == "true")
                projects = projects.Where(p => p.ProjectStatusId == (int)ProjectStatusType.Awaiting || p.ProjectStatusId == (int)ProjectStatusType.Ongoing);

            var vms = projects.ProjectTo<IndexProjectViewModel>();
            var projectsVm = vms.ToDataSourceResult(request);
            return Json(projectsVm);
        }

        // GET: Project/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var project = _projectRepository.GetByKey(id);
            if (project == null)
            {
                return HttpNotFound();
            }

            SetCreatedModifiedInViewBag(project);
            var vm = _mapper.Map<IndexProjectViewModel>(project);

            return View(vm);
        }

        // GET: Project/Create
        [PopulateAdvisors]
        [PopulateConstructionPrograms]
        [PopulateEntrepreneurs]
        [PopulateEntrepreneurCompanies]
        [PopulateProjectCategories]
        [PopulateLocalCommunities]
        [PopulateCouncils]
        [PopulateProjectLeaders]
        [PopulateCompanies]
        [PopulateTopics]
        [PopulateTeams]
        [PopulateProjectStatuses]
        [PopulateStreetTypes]
        [PopulatePlannings]
        [PopulateCouncilPriorities]
        [PopulateMunicipalityPriorities]
        [PopulateRequestors]
        [PopulateInconveniences]
        [PopulateTrafficInconveniences]
        [AddStatusExplanationUrl]
        public ActionResult Create()
        {
            var vm = new CreateProjectViewModel();
            return View(vm);
        }

        // POST: Project/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [PopulateAdvisors]
        [PopulateConstructionPrograms]
        [PopulateEntrepreneurs]
        [PopulateEntrepreneurCompanies]
        [PopulateProjectCategories]
        [PopulateLocalCommunities]
        [PopulateCouncils]
        [PopulateProjectLeaders]
        [PopulateCompanies]
        [PopulateTopics]
        [PopulateTeams]
        [PopulateProjectStatuses]
        [PopulateStreetTypes]
        [PopulatePlannings]
        [PopulateCouncilPriorities]
        [PopulateMunicipalityPriorities]
        [PopulateRequestors]
        [PopulateInconveniences]
        [PopulateTrafficInconveniences]
        [AddStatusExplanationUrl]
        public ActionResult Create(CreateProjectViewModel createProjectViewModel)
        {
            if (!ValidateInconvenience(createProjectViewModel))
            {
                AddInconvenienceModelError();
            }

            if (!ValidateTrafficInconvenience(createProjectViewModel))
            {
                AddTrafficInconvenienceModelError();
            }

            if (!ModelState.IsValid)
            {
                return View(createProjectViewModel);
            }

            var project = _mapper.Map<Project>(createProjectViewModel);

            if (project.Documents != null)
            {
                var guidList = project.Documents.Select(o => o.Guid).ToList();
                project.Documents.Clear();

                // foreach guid in vm, get document from db and insert in created project
                foreach (var guid in guidList)
                {
                    var guid1 = guid;
                    var document = _documentRepository.Get(o => o.Guid == guid1).First();
                    project.Documents.Add(document);
                }
            }
            project.CreatedBy = _adHelper.Name;
            project.CreatedOn = _dateTime.Now;

            // lookup for topic
            var topic = _topicRepo.GetByKey(createProjectViewModel.TopicId);
            if (topic != null)
            {
                project.Topic = topic;
            }

            // add spatialobject
            var spatialObject = _geoCoder.GetSpatialObject(createProjectViewModel.AddressId);
            project.AddressLocation = spatialObject;
            project.AddressLocationSRID = spatialObject.CoordinateSystemId;

            // Fetch address details from server and save to local DB
            var addr = _dawaRepo.GetAddress(createProjectViewModel.AddressId);
            project.AddressStreetName = addr.StreetName;
            project.AddressNumber = addr.Number;
            project.AddressZipCode = addr.ZipCode;
            project.AddressCity = addr.City;

            _projectRepository.Insert(project);
            _unitOfWork.Save();

            return RedirectToAction("Index");
        }

        // GET: Project/Edit/5
        [PopulateAdvisors]
        [PopulateConstructionPrograms]
        [PopulateEntrepreneurs]
        [PopulateEntrepreneurCompanies]
        [PopulateGroups]
        [PopulateProjectCategories]
        [PopulateLocalCommunities]
        [PopulateCouncils]
        [PopulateProjectLeaders]
        [PopulateCompanies]
        [PopulateTopics]
        [PopulateTeams]
        [PopulateProjectStatuses]
        [PopulateStreetTypes]
        [PopulatePlannings]
        [PopulateCouncilPriorities]
        [PopulateMunicipalityPriorities]
        [PopulateRequestors]
        [PopulateInconveniences]
        [PopulateTrafficInconveniences]
        [AddStatusExplanationUrl]
        public ActionResult Edit(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var project = _projectRepository.GetByKey(id);
            if (project == null) return HttpNotFound();

            SetCreatedModifiedInViewBag(project);
            var vm = _mapper.Map<EditProjectViewModel>(project);

            if (project.Advisor != null)
                vm.CompanyId = project.Advisor.CompanyId;

            if (project.Entrepreneur != null)
                vm.EntrepreneurCompanyId = project.Entrepreneur.CompanyId;

            if (project.ProjectLeader != null)
                vm.TeamId = project.ProjectLeader.TeamId;

            return View(vm);
        }

        // POST: Project/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [PopulateAdvisors]
        [PopulateConstructionPrograms]
        [PopulateEntrepreneurs]
        [PopulateEntrepreneurCompanies]
        [PopulateGroups]
        [PopulateProjectCategories]
        [PopulateLocalCommunities]
        [PopulateCouncils]
        [PopulateProjectLeaders]
        [PopulateCompanies]
        [PopulateTopics]
        [PopulateTeams]
        [PopulateProjectStatuses]
        [PopulateStreetTypes]
        [PopulatePlannings]
        [PopulateCouncilPriorities]
        [PopulateMunicipalityPriorities]
        [PopulateRequestors]
        [PopulateInconveniences]
        [PopulateTrafficInconveniences]
        [AddStatusExplanationUrl]
        public ActionResult Edit(EditProjectViewModel editProjectViewModel)
        {
            var project = _projectRepository.GetByKey(editProjectViewModel.Id);

Presentation.Web/Controllers/SearchController.cs
#region Head
// <copyright file="SearchController.cs" company="IT Minds" year="2015">
//     All rights reserved.
// </copyright>
// <license>
//     Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
// </license>
#endregion

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using Core.ApplicationServices;
using Core.DomainModel;
using Core.DomainServices;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Ninject.Infrastructure.Language;
using Presentation.Web.Attributes;
using Presentation.Web.Filters;
using Presentation.Web.Helpers;
using Presentation.Web.Models.Search;

namespace Presentation.Web.Controllers
{
    [AuthorizeRoles(UserRole.User, UserRole.Admin)]
    public class SearchController : BaseController
    {
        private readonly IMapper _mapper;
        private readonly ISearchService _searchService;
        private readonly IGenericRepository<Project> _projectRepository;
        private readonly IGenericRepository<AgendaPoint> _agendaPointRepository;

        public SearchController(IMapper mapper, ISearchService searchService, IGenericRepository<Project> projectRepository, IGenericRepository<AgendaPoint> agendaPointRepository)
        {
            _mapper = mapper;
            _searchService = searchService;
            _projectRepository = projectRepository;
            _agendaPointRepository = agendaPointRepository;
        }

        // GET: Search
        [PopulateTopics]
        [PopulateCouncilsRaw]
        [PopulateGroups]
        [PopulateCompanies(ShowInactives = true)]
        [PopulateEntrepreneurCompanies(ShowInactives = true)]
        [PopulateProjectStatuses(ShowInactives = true)]
        [PopulateMunicipalityPriorities(ShowInactives = true)]
        [PopulateCouncilPriorities(ShowInactives = true)]
        [PopulatePlannings(ShowInactives = true)]
        [PopulateAgendaPointStatuses(ShowInactives = true)]
        [PopulateRequestors(ShowInactives = true)]
        [PopulateLocalCommunities]
        [PopulateProjectCategories]
        public ActionResult Index(SearchViewModel viewModel)
        {
            if (viewModel == null)
            {
                viewModel = new SearchViewModel();
            }

            return View(viewModel);
        }

        // POST: Search
        [HttpPost, ActionName("Index")]
        [PopulateTopics]
        [PopulateCouncilsRaw]
        [PopulateGroups]
        [PopulateCompanies(ShowInactives = true)]
        [PopulateEntrepreneurCompanies(ShowInactives = true)]
        [PopulateProjectStatuses(ShowInactives = true)]
        [PopulateMunicipalityPriorities(ShowInactives = true)]
        [PopulateCouncilPriorities(ShowInactives = true)]
        [PopulatePlannings(ShowInactives = true)]
        [PopulateAgendaPointStatuses(ShowInactives = true)]
        [PopulateRequestors(ShowInactives = true)]
        [PopulateProjectCategories]
        [PopulateLocalCommunities]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> IndexPost(SearchViewModel viewModel)
        {
            if (viewModel == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (!viewModel.AnyParametersSet())
            {
                ViewBag.NoSearchParameters = true;
                return View(viewModel);
            }

            var results = new ResultsViewModel();
            if (viewModel.SearchInProjects)
            {
                var projectSearchParameters = _mapper.Map<ProjectSearchParameters>(viewModel);
                var projectsFilter = SearchHelper.ConstructFilterFuncProjectFromSearchParams(projectSearchParameters);

                results.ShowProjects = SearchHelper.ProjectFilterActuallyFilters(projectSearchParameters);
                results.ProjectFilter = projectsFilter;
                results.ProjectSearchParameters = projectSearchParameters;
            }
            if (viewModel.SearchInAgendaPoints)
            {
                var agendaPointSearchParameters = _mapper.Map<AgendaPointSearchParameters>(viewModel);
                var agendaPointsFilter = SearchHelper.ConstructFilterFuncAgendaPointFromSearchParams(agendaPointSearchParameters);

                results.ShowAgendaPoints = SearchHelper.AgendaPointFilterActuallyFilters(agendaPointSearchParameters);
                results.AgendaPointFilter = agendaPointsFilter;
                results.AgendaPointSearchParameters = agendaPointSearchParameters;
            }


            return View("Results", results);
        }

        // Til Kendo Grids Ajax kald.
        [HttpPost]
        public ActionResult AgendaPoint_Read([DataSourceRequest] DataSourceRequest request)
        {
            var agendaPoints = _agendaPointRepository.AsQueryable();

            var agendaPointsVm = agendaPoints.ProjectTo<AgendaPointViewModel>();
            var queryResultAgendaPoints = agendaPointsVm.ToDataSourceResult(request);
            return Json(queryResultAgendaPoints);
        }
        // Til Kendo Grids Ajax kald.
        [HttpPost]
        public ActionResult Project_Read([DataSourceRequest] DataSourceRequest request)
        {
            var projects = _projectRepository.AsQueryable();

            var projectsVm = projects.ProjectTo<ProjectViewModel>();
            var queryResultAgendaPoints = projectsVm.ToDataSourceResult(request);
            return Json(queryResultAgendaPoints);
        }

        private string CouncilGroupNameOrNull(ProjectViewModel vm)
        {
            return vm.Council != null ? vm.Council.Group.Name : null;
        }

        public ActionResult PrintSearchResults(ProjectSearchParameters searchParams)
        {
            var projects = _searchService.GetProjects(searchParams);
            var vmEnumerable = _mapper.Map<IEnumerable<ProjectViewModel>>(projects);
            var vmDictionary = FormatProjectsForPrintDisplay(vmEnumerable);

            return View(vmDictionary);
        }

        public ActionResult PrintSearchResultsDetailed(ProjectSearchParameters searchParams)
        {
            var projects = _searchService.GetProjects(searchParams);
            var vmEnumerable = _mapper.Map<IEnumerable<ProjectViewModel>>(projects);
            var vmDictionary = FormatProjectsForPrintDisplay(vmEnumerable);

            return View(vmDictionary);
        }

        public ActionResult PrintAgendaPointResults(AgendaPointSearchParameters searchParams)
        {
            var projects = _searchService.GetAgendaPoints(searchParams);
            var vms = _mapper.Map<IEnumerable<AgendaPointViewModel>>(projects);

            return View(vms);
        }

        private Dictionary<string, IEnumerable<ProjectViewModel>> FormatProjectsForPrintDisplay(IEnumerable<ProjectViewModel> projects)
        {
            return projects.ToList()
                      .GroupBy(CouncilGroupNameOrNull)
                      .OrderBy(grp => grp.Key, new StringComparerNullLast())
                      .ToDictionary(
                          grp => grp.Key ?? "Projekter uden gruppe",
                          grp => grp.ToList()
                              .OrderBy(prj => prj.Council?.Name)
                              .ThenBy(prj => prj.Id)
                              .ToEnumerable()
                          );
        }
    }
}

Presentation.Web/Views/Search/Index.cshtml
@model Presentation.Web.Models.Search.SearchViewModel
@{
    ViewBag.Title = "Søg";
}

<h2>Søg</h2>
<hr class="hidden-xs" />

@if (ViewBag.NoSearchParameters == true)
{
    <p class="text-danger">Indtast minimum ét søgekriterie og afkryds minimum én boks.</p>
}

@using (Html.BeginForm("Index", "Search", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.Address, new {@class = "control-label col-sm-3"})
            <div class="col-sm-9">
                @{
                    var selectedAddress = new List<SelectListItem> { new SelectListItem() }; // Empty item to enable dropdown clearing with select2
                    if (Model != null)
                    {
                        selectedAddress.Add(new SelectListItem {Value = Model.Address, Selected = true});
                    }
                }
                @Html.DropDownListFor(model => model.Address, selectedAddress, new {@class = "form-control", id = "address-search", style = "width: 100%", data_only_road_names = "1"})
                @Html.ValidationMessageFor(model => model.Address, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TemporaryAddressName, new { @class = "control-label col-sm-3" })
            <div class="col-sm-9">
                @Html.EditorFor(model => model.TemporaryAddressName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TemporaryAddressName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectStatusId, new { @class = "control-label col-sm-3" })
            <div class="col-sm-9">
                @Html.DropDownListFor(model => model.ProjectStatusId, ViewBag.ProjectStatusList as List<SelectListItem>, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProjectStatusId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AgendaPointStatusId, new { @class = "control-label col-sm-3" })
            <div class="col-sm-9">
                @Html.DropDownListFor(m => m.AgendaPointStatusId, ViewBag.AgendaPointStatusList as List<SelectListItem>, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AgendaPointStatusId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TopicIds, new { @class = "control-label col-sm-3" })
            <div class="col-sm-9">
                <div>
                    <select id="topic-multi-select" name="TopicIds" multiple="multiple" class="form-control">
                        @foreach (var topic in ViewBag.TopicList)
                        {
                            <option value="@topic.Value">@topic.Text</option>
                        }
                    </select>
                </div>
                @Html.ValidationMessageFor(model => model.TopicIds, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectId, new {@class = "control-label col-sm-3"})
            <div class="col-sm-9">
                @Html.EditorFor(model => model.ProjectId, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.ProjectId, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MeetingId, new {@class = "control-label col-sm-3"})
            <div class="col-sm-9">
                @Html.EditorFor(model => model.MeetingId, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.MeetingId, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GroupId, new { @class = "control-label col-sm-3" })
            <div class="col-sm-9">
                @Html.DropDownListFor(model => model.GroupId, ViewBag.GroupList as List<SelectListItem>, "", new { @class = "form-control", @id = "GroupSelect" })
                @Html.ValidationMessageFor(model => model.GroupId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CouncilId, new {@class = "control-label col-sm-3"})
            <div class="col-sm-9">
                <select name="@Html.NameFor(model => model.CouncilId)" id="CouncilSelect" class="form-control">
                    <option value=""></option>
                    @foreach (var council in ViewBag.Councils)
                    {
                        <option value="@council.Id" data-group-id="@council.GroupId">@council.Name</option>
                    }
                </select>
                @Html.ValidationMessageFor(model => model.CouncilId, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocalCommunityId, new { @class = "control-label col-sm-3" })
            <div class="col-sm-9">
                @Html.DropDownListFor(model => model.LocalCommunityId, ViewBag.LocalCommunityList as List<SelectListItem>, "", new { @class = "form-control", @id = "LocalCommunitySelect" })
                @Html.ValidationMessageFor(model => model.LocalCommunityId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectCategoryId, new { @class = "control-label col-sm-3" })
            <div class="col-sm-9">
                @Html.DropDownListFor(model => model.ProjectCategoryId, ViewBag.ProjectCategoryList as List<SelectListItem>, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProjectCategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyId, new { @class = "control-label col-sm-3" })
            <div class="col-sm-9">
                @Html.DropDownListFor(model => model.CompanyId, ViewBag.CompanyList as List<SelectListItem>, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CompanyId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EntrepreneurCompanyId, new { @class = "control-label col-sm-3" })
            <div class="col-sm-9">
                @Html.DropDownListFor(model => model.EntrepreneurCompanyId, ViewBag.EntrepreneurCompanyList as List<SelectListItem>, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EntrepreneurCompanyId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestorId, new { @class = "control-label col-sm-3" })
            <div class="col-sm-9">
                @Html.DropDownListFor(model => model.RequestorId, ViewBag.RequestorList as List<SelectListItem>, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RequestorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, new {@class = "control-label col-sm-3"})
            <div class="col-sm-3">
                @Html.EnumDropDownListFor(model => model.DateSearchType, new { @class = "form-control" })
            </div>
            <div class="col-sm-3">
                @Html.EditorFor(model => model.StartDate, new {htmlAttributes = new {@class = "form-control", placeholder = "Fra"}})
                @Html.ValidationMessageFor(model => model.StartDate, "", new {@class = "text-danger"})
            </div>
            <div class="col-sm-3">
                @Html.EditorFor(model => model.EndDate, new {htmlAttributes = new {@class = "form-control", placeholder = "Til"}})
                @Html.ValidationMessageFor(model => model.EndDate, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SearchInAgendaPoints, new {@class = "control-label col-sm-3"})
            <div class="col-sm-9">
                @Html.CheckBoxFor(model => model.SearchInAgendaPoints, new {@class = "checkbox"})
                @Html.ValidationMessageFor(model => model.SearchInAgendaPoints, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SearchInProjects, new {@class = "control-label col-sm-3"})
            <div class="col-sm-9">
                @Html.CheckBoxFor(model => model.SearchInProjects, new {@class = "checkbox"})
                @Html.ValidationMessageFor(model => model.SearchInProjects, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-2 col-xs-4 col-sm-offset-3">
                <input type="submit" value="Søg" class="form-control btn btn-success"/>
            </div>
            <div class="col-sm-7 col-xs-8">
                <input type="reset" value="Nulstil" class="btn btn-danger"/>
            </div>
        </div>
    </div>
}

@section scripts
{
    <script type="text/javascript">
        $(function() {
            var groupSelect = $('#GroupSelect');
            var councilSelect = $('#CouncilSelect');
            var allOptions = new Array();

            councilSelect.find('option').each(function () {
                if ($(this).val() !== '') {
                    allOptions.push({
                        value: $(this).val(),
                        text: $(this).text(),
                        groupId: $(this).attr('data-group-id'),
                    });
                }
            });

            var filterCouncils = function() {
                var selectedGroup = groupSelect.val();

                councilSelect.empty();
                $('<option></option>').appendTo(councilSelect);

                $(allOptions).each(function(i, option) {
                    var councilGroup = $(this).attr('data-group-id');

                    if (selectedGroup === '' || selectedGroup === option.groupId)
                        $('<option></option>').val(option.value).text(option.text).appendTo(councilSelect);
                });
            };

            groupSelect.on('change', filterCouncils);

            $("#topic-multi-select").select2();
        });
    </script>
}

Presentation.Web/Views/Search/PrintSearchResults.cshtml
@using Presentation.Web.Models.Search
@model IEnumerable<KeyValuePair<string, IEnumerable<ProjectViewModel>>>

@{
    ViewBag.Title = "Fremsøgte projekter";
}

<h2 class="page-header">@ViewBag.Title</h2>

<button class="hidden-print btn btn-primary pull-right" onclick="printPage()">
    <span class="glyphicon glyphicon-print"></span>
    <span> Print projekter</span>
</button>

@foreach (var projectGrouping in Model)
{
    <h4>@(projectGrouping.Key)</h4>
    foreach (var project in projectGrouping.Value)
    {
        if (project.Council != null)
        {
            <h6>Fællesråd: @project.Council.Name</h6>
        }

        @Html.Partial("_PrintResultsPartial", project)
    }
    <hr class="printing-new-page" />
}

@section Scripts{
    <script>
        function printPage() {
            window.print();
        }
    </script>
}

Presentation.Web/Views/Search/PrintSearchResultsDetailed.cshtml
@using Presentation.Web.Models.Search
@model IEnumerable<KeyValuePair<string, IEnumerable<ProjectViewModel>>>

@{
    ViewBag.Title = "Fremsøgte projekter med detaljer";
}

<h2 class="page-header">@ViewBag.Title</h2>

<button class="hidden-print btn btn-primary pull-right" onclick="printPage()">
    <span class="glyphicon glyphicon-print"></span>
    <span> Print projekter med detaljer</span>
</button>

@foreach (var projectGrouping in Model)
{
    <h4>@(projectGrouping.Key)</h4>
    foreach (var project in projectGrouping.Value)
    {
        if (project.Council != null)
        {
            <h6>Fællesråd: @project.Council.Name</h6>
        }

        @Html.Partial("_PrintResultsDetailedPartial", project)
    }
    <hr class="printing-new-page"/>
}

@section Scripts
{
    <script>
        function printPage() {
            window.print();
        }
    </script>
}