Presentation.Web/Models/Advisor/AdvisorDTO.cs
#region Head
// <copyright file="AdvisorDTO.cs" company="IT Minds" year="2016">
//     All rights reserved.
// </copyright>
// <license>
//     Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
// </license>
#endregion
namespace Presentation.Web.Models.Advisor
{
    public class AdvisorDTO
    {
        public int Id { get; set; }
        public string ResponsiblePersonName { get; set; }
    }
}

Presentation.Web/Models/Advisor/CreateAdvisorViewModel.cs
#region Head
// <copyright file="AddAdvisorViewModel.cs" company="IT Minds" year="2015">
//     All rights reserved.
// </copyright>
// <license>
//     Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
// </license>
#endregion
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Presentation.Web.Filters;
using Presentation.Web.Models.Shared;

namespace Presentation.Web.Models.Advisor
{
    public class CreateAdvisorViewModel : CbaListPropertiesViewModel, ISelectedCompany
    {
        public CreateAdvisorViewModel()
        {
            IsActive = true;
        }
        [DisplayName("Virksomhed*")]
        [Required(ErrorMessage="Virksomhedsnavn er påkrævet.")]
        public int? CompanyId { get; set; }

        [DisplayName("Kontaktperson*")]
        [Required(ErrorMessage = "Kontaktperson er påkrævet.")]
        public string ResponsiblePersonName { get; set; }

        [DisplayName("Telefonnummer*")]
        [Required(ErrorMessage = "Telefonnummer er påkrævet.")]
        public string ResponsiblePersonPhoneNumber { get; set; }
    }
}

Presentation.Web/Models/Advisor/DeleteAdvisorViewModel.cs
#region Head
// <copyright file="DeleteAdvisorViewModel.cs" company="IT Minds" year="2015">
//     All rights reserved.
// </copyright>
// <license>
//     Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
// </license>
#endregion

using Presentation.Web.Models.Shared;

namespace Presentation.Web.Models.Advisor
{
    using System.ComponentModel;

    public class DeleteAdvisorViewModel : CbaListPropertiesViewModel
    {
        [DisplayName("Virksomhed")]
        public string CompanyName { get; set; }
        [DisplayName("Kontaktperson")]
        public string ResponsiblePersonName { get; set; }
        [DisplayName("Telefonnummer")]
        public string ResponsiblePersonPhoneNumber { get; set; }
    }
}

Presentation.Web/Models/Advisor/EditAdvisorViewModel.cs
#region Head
// <copyright file="EditAdvisorViewModel.cs" company="IT Minds" year="2015">
//     All rights reserved.
// </copyright>
// <license>
//     Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
// </license>
#endregion

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Presentation.Web.Filters;
using Presentation.Web.Models.Shared;

namespace Presentation.Web.Models.Advisor
{
    public class EditAdvisorViewModel : CbaListPropertiesViewModel, ISelectedCompany
    {
        public int Id { get; set; }

        [DisplayName("Virksomhed*")]
        [Required(ErrorMessage = "Virksomhedsnavn er påkrævet.")]
        public int? CompanyId { get; set; }

        [DisplayName("Kontaktperson*")]
        [Required(ErrorMessage = "Kontaktperson er påkrævet.")]
        public string ResponsiblePersonName { get; set; }

        [DisplayName("Telefonnummer*")]
        [Required(ErrorMessage = "Telefonnummer er påkrævet.")]
        public string ResponsiblePersonPhoneNumber { get; set; }
    }
}

Presentation.Web/Models/Advisor/IndexAdvisorViewModel.cs
#region Head
// <copyright file="AdvisorViewModel.cs" company="IT Minds" year="2015">
//     All rights reserved.
// </copyright>
// <license>
//     Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
// </license>
#endregion
using System.ComponentModel;
using Presentation.Web.Models.Company;
using Presentation.Web.Models.Shared;

namespace Presentation.Web.Models.Advisor
{
    public class IndexAdvisorViewModel : CbaListPropertiesViewModel
    {
        public int Id { get; set; }

        [DisplayName("Virksomhed")]
        public IndexCompanyViewModel Company { get; set; }

        [DisplayName("Kontaktperson")]
        public string ResponsiblePersonName { get; set; }

        [DisplayName("Telefonnummer")]
        public string ResponsiblePersonPhoneNumber { get; set; }
    }
}

Presentation.Web/Controllers/AdvisorController.cs
#region Head
// <copyright file="AdvisorController.cs" company="IT Minds" year="2015">
//     All rights reserved.
// </copyright>
// <license>
//     Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
// </license>
#endregion

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using Core.DomainModel;
using Core.DomainServices;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Presentation.Web.Attributes;
using Presentation.Web.Filters;
using Presentation.Web.Helpers;
using Presentation.Web.Models.Advisor;

namespace Presentation.Web.Controllers
{
    [AuthorizeRoles(UserRole.Admin)]
    public class AdvisorController : BaseController
    {
        private readonly IGenericRepository<Advisor> _repo;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        private readonly IAdHelper _adHelper;

        public AdvisorController(IGenericRepository<Advisor> repo, IUnitOfWork unitOfWork, IMapper mapper, IAdHelper adHelper)
        {
            _repo = repo;
            _unitOfWork = unitOfWork;
            _mapper = mapper;
            _adHelper = adHelper;
        }

        // GET: Advisor
        [PopulateCompanies]
        public ActionResult Index()
        {
            return View();
        }

        // Til Kendo Grids Ajax kald.
        [HttpPost]
        public ActionResult Advisor_Read([DataSourceRequest] DataSourceRequest request)
        {
            var advisors = _repo.AsQueryable().Where(a => !a.IsDeleted);

            var vms = advisors.ProjectTo<IndexAdvisorViewModel>();

            var advisorVm = vms.ToDataSourceResult(request);
            return Json(advisorVm);
        }

        // GET: Advisor/:companyId
        // Returns all advisors with company id
        public ActionResult AdvisorsWithCompanyId(int? companyId)
        {
            var advisors = _repo.AsQueryable().Where(a => !a.IsDeleted && a.IsActive && a.Company.IsActive);
            if (companyId != null)
                advisors = advisors.Where(a => a.CompanyId == companyId);

            // have to sort it in memory as the database sort æøå wrong and doesn't recognize StringComparer.CurrentCulture
            // WARN make sure this order matches the order in PopulateAdvisorsFilter and visa versa
            var orderedAdvisors = advisors.ToList().OrderBy(x => x.ResponsiblePersonName, StringComparer.CurrentCulture);

            var advisorDTOs = _mapper.Map<IEnumerable<AdvisorDTO>>(orderedAdvisors);
            return Json(advisorDTOs, JsonRequestBehavior.AllowGet);
        }

        // GET: Advisor/Create
        [PopulateCompanies]
        public ActionResult Create()
        {
            var vm = new CreateAdvisorViewModel();
            return View(vm);
        }

        // POST: Advisor/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [PopulateCompanies]
        public ActionResult Create(CreateAdvisorViewModel addAdvisorViewModel)
        {
            if (!ModelState.IsValid) return View(addAdvisorViewModel);

            var advisor = _mapper.Map<Advisor>(addAdvisorViewModel);
            advisor.CreatedOn = DateTime.Now;
            advisor.CreatedBy = _adHelper.Name;

            _repo.Insert(advisor);
            _unitOfWork.Save();

            return RedirectToAction("Index");
        }

        // GET: Advisor/Edit/{id}
        [PopulateCompanies]
        public ActionResult Edit(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var advisor = _repo.GetByKey(id);
            if (advisor == null || advisor.IsDeleted) return HttpNotFound();

            SetCreatedModifiedInViewBag(advisor);

            var vm = _mapper.Map<EditAdvisorViewModel>(advisor);

            return View(vm);
        }

        // POST: Advisors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [PopulateCompanies]
        public ActionResult Edit(EditAdvisorViewModel editAdvisorViewModel)
        {
            if (!ModelState.IsValid)
            {
                var logger = _repo.GetByKey(editAdvisorViewModel.Id) as Logger;
                SetCreatedModifiedInViewBag(logger);
                return View(editAdvisorViewModel);
            }

            var advisor = _mapper.Map<Advisor>(editAdvisorViewModel);
            advisor.ModifiedOn = DateTime.Now;
            advisor.ModifiedBy = _adHelper.Name;

            _repo.Update(advisor);
            _unitOfWork.Save();

            return RedirectToAction("Index");
        }

        // GET: Advisors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var advisor = _repo.GetByKey(id);
            if (advisor == null || advisor.IsDeleted) return HttpNotFound();
            SetCreatedModifiedInViewBag(advisor);

            var vm = _mapper.Map<DeleteAdvisorViewModel>(advisor);

            return View(vm);
        }

        // POST: Advisors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (id <= 0) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var advisor = _repo.GetByKey(id);
            if (advisor == null || advisor.IsDeleted) return HttpNotFound();

            advisor.IsDeleted = true;

            _repo.Update(advisor);
            _unitOfWork.Save();

            return RedirectToAction("Index");
        }
    }
}

Presentation.Web/Controllers/CompanyController.cs
#region Head
// <copyright file="CompanyController.cs" company="IT Minds" year="2016">
//     All rights reserved.
// </copyright>
// <license>
//     Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
// </license>
#endregion
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using Core.DomainModel;
using Core.DomainServices;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Presentation.Web.Helpers;
using Presentation.Web.Models.Company;

namespace Presentation.Web.Controllers
{
    public class CompanyController : BaseController
    {
        private readonly IGenericRepository<Company> _repo;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        private readonly IAdHelper _adHelper;

        public CompanyController(IGenericRepository<Company> repo, IUnitOfWork unitOfWork, IMapper mapper, IAdHelper adHelper)
        {
            _repo = repo;
            _unitOfWork = unitOfWork;
            _mapper = mapper;
            _adHelper = adHelper;
        }

        // GET: Company
        public ActionResult Index()
        {
            return View();
        }

        // Til Kendo Grids Ajax kald.
        [HttpPost]
        public ActionResult Company_Read([DataSourceRequest] DataSourceRequest request)
        {
            var companies = _repo.AsQueryable().Where(a => !a.IsDeleted);

            var vms = companies.ProjectTo<IndexCompanyViewModel>();

            var companyVm = vms.ToDataSourceResult(request);
            return Json(companyVm);
        }

        // GET: Company/Create
        public ActionResult Create()
        {
            var vm = new CreateCompanyViewModel();
            return View(vm);
        }

        // POST: Company/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateCompanyViewModel addCompanyViewModel)
        {
            if (!ModelState.IsValid) return View(addCompanyViewModel);

            var company = _mapper.Map<Company>(addCompanyViewModel);
            company.CreatedOn = DateTime.Now;
            company.CreatedBy = _adHelper.Name;

            _repo.Insert(company);
            _unitOfWork.Save();

            return RedirectToAction("Index");
        }

        // GET: Company/Edit/{id}
        public ActionResult Edit(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var company = _repo.GetByKey(id);
            if (company == null || company.IsDeleted) return HttpNotFound();

            SetCreatedModifiedInViewBag(company);

            var vm = _mapper.Map<EditCompanyViewModel>(company);

            return View(vm);
        }

        // POST: Company/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditCompanyViewModel editCompanyViewModel)
        {
            if (!ModelState.IsValid)
            {
                var logger = _repo.GetByKey(editCompanyViewModel.Id) as Logger;
                SetCreatedModifiedInViewBag(logger);
                return View(editCompanyViewModel);
            }

            var company = _mapper.Map<Company>(editCompanyViewModel);
            company.ModifiedOn = DateTime.Now;
            company.ModifiedBy = _adHelper.Name;

            _repo.Update(company);
            _unitOfWork.Save();

            return RedirectToAction("Index");
        }

        // GET: Company/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var company = _repo.GetByKey(id);
            if (company == null || company.IsDeleted) return HttpNotFound();
            SetCreatedModifiedInViewBag(company);

            var vm = _mapper.Map<DeleteCompanyViewModel>(company);
            vm.CanDelete = company.Advisors.All(x => x.IsDeleted);

            return View(vm);
        }

        // Delete: Company/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (id <= 0) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var company = _repo.GetByKey(id);
            if (company == null || company.IsDeleted) return HttpNotFound();

            if (company.Advisors.Any(x => x.IsDeleted == false))
                return RedirectToAction("Index"); // abort if any none deleted advisors exists

            company.IsDeleted = true;

            _repo.Update(company);
            _unitOfWork.Save();

            return RedirectToAction("Index");
        }
    }
}

Presentation.Web/Views/Advisor/Create.cshtml
@model Presentation.Web.Models.Advisor.CreateAdvisorViewModel
@{
    ViewBag.Title = "Opret rådgiver";
}

<h2>Opret rådgiver</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CompanyId, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.CompanyId, ViewBag.CompanyList as List<SelectListItem>, "Vælg virksomhed", new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.CompanyId, "", new {@class = "text-danger"})
            </div>
            <div class="col-md-10 col-md-offset-2">
                <a href="@Url.Action("Create", "Company")"><span class="glyphicon glyphicon-plus text-success"></span> Opret virksomhed</a>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ResponsiblePersonName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ResponsiblePersonName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ResponsiblePersonName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ResponsiblePersonPhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ResponsiblePersonPhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ResponsiblePersonPhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, new { @class = "control-label col-xs-2" })
            <div class="col-xs-10">
                @Html.EditorFor(model => model.IsActive, new { htmlAttributes = new { @class = "checkbox" } })
                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Gem" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tilbage til listen", "Index")
</div>

Presentation.Web/Views/Advisor/Delete.cshtml
@model Presentation.Web.Models.Advisor.DeleteAdvisorViewModel

@{
    ViewBag.Title = "Bekræft sletning";
}

<h2>Bekræft sletning</h2>

@Html.Partial("CreatedModifiedPartialView")

<hr class="hidden-xs" />

<h3>Er du sikker på at du vil slette denne rådgiver?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResponsiblePersonName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ResponsiblePersonName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResponsiblePersonPhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ResponsiblePersonPhoneNumber)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Slet" class="btn btn-danger" /> |
            @Html.ActionLink("Tilbage til listen", "Index")
        </div>
    }
</div>

Presentation.Web/Views/Advisor/Edit.cshtml
@model Presentation.Web.Models.Advisor.EditAdvisorViewModel
@{
    ViewBag.Title = "Rediger rådgiver";
}

<h2>Rediger rådgiver</h2>
@Html.Partial("CreatedModifiedPartialView")

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.CreatedOn)
    @Html.HiddenFor(model => model.CreatedBy)

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.CompanyId, ViewBag.CompanyList as List<SelectListItem>, "Vælg virksomhed", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CompanyId, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-10 col-md-offset-2">
                <a href="@Url.Action("Create", "Company")"><span class="glyphicon glyphicon-plus text-success"></span> Opret virksomhed</a>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ResponsiblePersonName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ResponsiblePersonName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ResponsiblePersonName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ResponsiblePersonPhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ResponsiblePersonPhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ResponsiblePersonPhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, new { @class = "control-label col-xs-2" })
            <div class="col-xs-10">
                @Html.EditorFor(model => model.IsActive, new { htmlAttributes = new { @class = "checkbox" } })
                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Gem" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tilbage til listen", "Index")
</div>

Presentation.Web/Views/Advisor/Index.cshtml
@using Presentation.Web.Helpers
@model IEnumerable<Presentation.Web.Models.Advisor.IndexAdvisorViewModel>
@{
    ViewBag.Title = "Rådgivere";
    var gridTitle = "AdvisorGrid";
}

<h2>Rådgivere</h2>
<div class="container">
    <div class="row">
        <a href="@Url.Action("Create")"><span class="glyphicon glyphicon-plus text-success"></span> Opret rådgiver</a>
    </div>
    <hr />
    @(Html.Kendo().Grid<Presentation.Web.Models.Advisor.IndexAdvisorViewModel>()
          .Name(gridTitle)
          .Columns(c =>
          {
              c.Bound(col => col.Company.Name)
                .Filterable(x => x.UI("filterCustomizationCompany")
                .Extra(false)
                .Messages(msg => msg.Info("Filtrer rækker med valgt virksomhed")));
              c.Bound(col => col.ResponsiblePersonName);
              c.Bound(col => col.ResponsiblePersonPhoneNumber);
              c.Bound(col => col.IsActive).ClientTemplate("# if (IsActive === true) { # " +
                                                                  "Ja" +
                                                                  "# } else { #" +
                                                                  "Nej" +
                                                                  "# } #");
              c.Template(col => null)
                  .AddCustomButton("<span class=\"glyphicon glyphicon-pencil text-success\"></span>", Url.Action("Edit", "Advisor"))
                  .AddCustomButton("<span class=\"glyphicon glyphicon-remove text-danger\"></span>", Url.Action("Delete", "Advisor")).Width(1);
          })
          .Pageable(pager => pager.PageSizes(new List<int> { 10, 20, 50, 100, 200, 500 }))
          .Sortable()
          .Filterable(x => x.Mode(GridFilterMode.Menu))
          .DataSource(x => x.Ajax().Read(r => r.Action("Advisor_Read", "Advisor")))
    )
</div>

@Scripts.Render("~/Scripts/kendo/KendoTableHelpers.js")


@section scripts
{
    <script>
        $(function() {
            initStatePersistance("@gridTitle");
        });

        function filterCustomizationCompany(element) {
            removeOperatorDropdown(element);

            // Change the text box for at dropdown with the values in the database
            element.kendoDropDownList({
                dataSource: @Html.Raw(Json.Encode((ViewBag.CompanyList as List<SelectListItem>).AsQueryable().Select(x => x.Text))),
                optionLabel: "Vælg virksomhed"
            });
        }
    </script>
}